/*
 * SWAPI
 *
 * This is a RESTful API SWAPI written in GO. You can find out more about SWAPI at [https://www.swapi.co](https://www.swapi.co). And you can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

 package main

 import (
	 "log"
	 "net/http"
 
	 // WARNING!
	 // Change this to a fully-qualified import path
	 // once you place this file into your project.
	 // For example,
	 //
	 //    sw "github.com/myname/myrepo/go"
	 //
	 sw "github.com/blesswxl/MySWAPI/go"
 )
 
 func main() {
	 log.Printf("Server started")
 
	 router := sw.NewRouter()
 
	 log.Fatal(http.ListenAndServe(":8080", router))
 }