/*
 * SWAPI
 *
 * This is a RESTful API SWAPI written in GO. You can find out more about SWAPI at [https://www.swapi.co](https://www.swapi.co). And you can find out more about Swagger at [http://swagger.io](http://swagger.io) or on [irc.freenode.net, #swagger](http://swagger.io/irc/). 
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"encoding/json"
	"net/http"
)

func GetAllAPI(w http.ResponseWriter, r *http.Request) {
    url := "http://localhost:8080" 
	w.Header().Set("Content-Type", "application/json; charset=UTF-8")
	w.WriteHeader(http.StatusOK)
    var root = Root{url + "/people/",
                    url + "/planets/",
                    url + "/species/",
                    url + "/vehicles/",
                    url + "/films/",
                    url + "/starships/"}
    data, _ := json.Marshal(root)
    w.Write([]byte(data))
}
